### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ph7jack** [sturdy-dev/codeball-action#196]
Hi, the codeball is failing on pipeline, also the website doesn't works
Thanks
![image](https://github.com/sturdy-dev/codeball-action/assets/38913462/56325f5d-fa4d-469f-85c5-3e4f91ac89ff)
![image](https://github.com/sturdy-dev/codeball-action/assets/38913462/f9f8d343-bcc7-4287-a7f8-e078f9eb8134)

**Comment by krlvi** [comment]
Hi @PH7-Jack — I am sorry for this disruption of the service. The app should be back online now, let me know if it's not working. 

I will get back with a more detailed update soon (I intend to open source the stack).
Thanks

**Comment by krlvi** [comment]
Closing this now, as the api appears to work
