### ISSUE TITLE
Permissions issue with forks (public repositories)

### ISSUE THREAD

**Issue by mattstratton** [sturdy-dev/codeball-action#43]
I'm a little confused by this portion `By default, pull requests from a fork does not have "write" permissions when running in GitHub Actions, and those Pull Requests can not be approved or labeled.`

We have a public repo with the GH action enabled. It works fine with my pull requests (branches in the repo). On PRs from forks, we get the error:
`Error: Codeball Labeler failed to access GitHub. Check the "GITHUB_TOKEN Permissions" of this job and make sure that the job has WRITE permissions to Pull Requests.`

Everything I can see makes it seem that is only the case for private repos: I have the job configured for `permissions: write-all` so I don't quite understand how to get this to work.

**Comment by mattstratton** [comment]
The repository is [devopsdays/devopsdays-web](https://github.com/devopsdays/devopsdays-web)

**Comment by zegl** [comment]
Hey @mattstratton! Cool to see that you've setup Codeball for devopsdays! 🧠

Permissions across forks can indeed be a bit tricky. By default, GitHub does not grant write access to the parent repository for actions run in a fork (and reasonably so).

Beware that there is a risk involved in granting write permissions to Pull Requests created from a fork (the token generated has write permissions after all).

You can go to the repository settings (at https://github.com/devopsdays/devopsdays-web/settings/actions) and enable the following settings to make it work. If you can't see the settings, go and check the org settings first (at https://github.com/organizations/devopsdays/settings/actions).

GitHub documents this and more related to permissions for GitHub actions here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#preventing-github-actions-from-creating-or-approving-pull-requests

When setup correctly, the settings should look like this:

<img width="797" alt="Screenshot 2022-06-16 at 15 21 05" src="https://user-images.githubusercontent.com/47952/174079103-4b4859cc-4f60-4896-ac13-e58eedfd4be7.png">

We've also been thinking about alternative ways to grant permissions to approve PRs from forks, so please let me know if this doesn't work out, and we can test some alternative setups together.

**Comment by mattstratton** [comment]
Hmm. That's how we have them set up already (granted, it only requires approval from first time contributors, which seems more lenient than your example, but I could try that...I'm worried it will be annoying in our use case where 98% of the PRs come from forks and there are several per week)![image](https://user-images.githubusercontent.com/1280666/174083861-d1b2595f-c6b8-4fb4-970b-ba33498132bb.jpeg) ![image](https://user-images.githubusercontent.com/1280666/174083883-d95ae2d4-f385-4508-baac-f12a39c2fa01.jpeg)

**Comment by zmstone** [comment]
Having the same issue, for PRs sent from forks, codeball does not have permission.

> The idea that we've had to work around this issue is to allow to install a GitHub App on the parent repository, and use the token of the application in this situation instead of using the token from the Action.

Not sure if I follow, have I done it right as below ?

<img width="399" alt="image" src="https://user-images.githubusercontent.com/164324/174286240-4175d22c-333d-4b1f-8c17-57bc483f961e.png">

**Comment by zegl** [comment]
> Not sure if I follow, have I done it right as below ?

We haven't built it yet, but maybe it's time! ;-D

**Comment by ngalaiko** [comment]
Hi @mattstratton @zmstone,

We've just published [v2.2.0](https://github.com/sturdy-dev/codeball-action/releases/tag/v2.2.0) of the action to address this issue.

Now, for cases as such, you can install [Codeball AI Writer](https://github.com/apps/codeball-ai-writer) action to your repo, and then we'll use application installation tokens to approve/label pull request from our servers.

**Comment by ngalaiko** [comment]
Closing this one. Feel free to reopen if something doesn't work for you
