### ISSUE TITLE
[question] Is the website/docs found at codeball.ai in a repo to contribute to?

### ISSUE THREAD

**Issue by ChrisCarini** [sturdy-dev/codeball-action#8]

**Comment by zegl** [comment]
Hey @ChrisCarini! The website is currently in the same codebase as some of our internal stuff, but I have no problem making the website itself open-source. I'll move it over to a new public repository on Monday! 👍

**Comment by ChrisCarini** [comment]
Sounds good, thank you!

**Comment by zegl** [comment]
The sources for the codeball.ai website are now up at https://github.com/sturdy-dev/codeball-web :-)
